# Your presentation title
title: Mundane Programming at SRCCON 2015
google_analytics_id: "UA-64284356-1"

# The Reveal theme
reveal_theme: solarized.css

# The Reveal transition
reveal_transition: default

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: reveal.js/css/theme/

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options:

# Additional reveal.js dependencies
reveal_dependencies:

# Reveal.js subdirectory
reveal_path: reveal.js/

# Don't change anything below
markdown: redcarpet
highlighter: pygments
markdown_ext: ignoreme

